config/routes.rb
Rails.application.routes.draw do
  

  get 'admin/index'

  get "/pages/:page" => "pages#show", as: 'static'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'

  }



  resources :workshop
  resources :email
  resources :seats
  resources :shows
  resources :store_items
  resources :teachers
  resources :lessons
  resources :enrollments
  resources :gift_cards
  resources :instructed_classes
  resources :home
  root "home#index"

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :instructed_class
  belongs_to :user
end

app/models/gift_card.rb
class GiftCard < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  belongs_to :user
end

app/models/instructed_class.rb
class InstructedClass < ApplicationRecord
  belongs_to :lesson
  belongs_to :teacher
  has_many :enrollments, dependent: :destroy
  has_many :users, through: :enrollment
  
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
	has_many :instructed_classes, dependent: :destroy
	has_many :teachers, through: :instructed_classes
end

app/models/seat.rb
class Seat < ApplicationRecord
	has_many :show_seatings
  has_many :shows, through: :show_seating
end

app/models/show.rb
class Show < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :show_seatings
  has_many :seats, through: :show_seatings
  accepts_nested_attributes_for :show_seatings, :allow_destroy => true
  accepts_nested_attributes_for :seats, :allow_destroy => true
end

app/models/show_seating.rb
class ShowSeating < ApplicationRecord
  belongs_to :seat
  belongs_to :show
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
	has_many :instructed_classes, dependent: :destroy
	has_many :lessons, through: :instructed_classes
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :user, :teacher], multiple: false)                                      ##
  ############################################################################################ 
 
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :email, :uniqueness => true
  # validates_inclusion_of :roles, in: ['admin', 'teacher', 'user']

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	has_many :shows
	has_many :gift_cards
	has_many :store_items
	has_many :enrollments
	has_many :instructed_classes, through: :enrollments
	

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
    def index
   
    @seat = Seat.new
    @seats = Seat.all
  end

  def new
    @seat = Seat.new
  end

  def create
    @seat = Seat.new
    respond_to do |format|
      @seat = Seat.create(seat_params)
      format.js
      format.html{redirect_to seats_index_path}
    end
  end

  def show
    @seats = Seat.all
    @seat = Seat.find(params[:id])
  end

  def edit
    @seat = Seat.find(params[:id])
  end

  def update
    @seat = Seat.find(params[:id])
    @seat.update(show_params)
    redirect_to shows_path
  end

  def destroy
     respond_to do |format|
      @seat = Seat.find(params[:id]).destroy
      format.js
      format.html{redirect_to seats_path}
    end
  end

   def seat_params
    params.require(:seat).permit(:section, :id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/gift_cards_helper.rb
module GiftCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/seats/_form.html.erb
<div class="form">
    <%= form_with model: @seat, class: "new_seat" do |f| %>
    
      <%# f.label :section %>
      <%= f.text_field :section, placeholder: 'section', class: "form-control", id: "section" %>
      <br>
      <br>
       <div class="black-text">
       	<%= f.submit %>
       </div>
    <% end %>
</div>	

app/views/seats/_seat.html.erb
<div class="col s3 m6 seats">
	    <div class="card horizontal">
	      <div class="card-stacked">
	        <div class="card-content">
	        	<span class="card-title">
	        		<p><%=  seat.section %></p>
	        </div>
	        <div class="card-action float_right">
	        	<%= link_to "delete", seat, method: :delete, remote: true, class: "destroy_show float_right"%>
	 	          <%= link_to "edit", edit_seat_path(seat), class: "float_right" %>
	        </div>
	      </div>
	    </div>
	  </div>

app/views/seats/create.js.erb
$('.teachers').prepend("<%= j render @seat %>");
$('.new_seat').trigger('reset');

app/views/seats/edit.html.erb
<div class="header">
	<h1>Edit Seating Chart</h1>
 	<div class="row">
	 	<div class="col l3 s3"></div>
	 	 <div class="col l6 s9">
	 	 	<div class="card grey darken-4">
	      <div class="card-content white-text">
	      	<%= render 'form' %>
	   		</div>
			</div>
		</div>
	</div>

app/views/seats/index.html.erb
<div class="header">
	<h1>Edit Seating Chart</h1>
 	<div class="row">
	 	<div class="col l3 s3"></div>
	 	 <div class="col l6 s9">
	 	 	<div class="card grey darken-4">
	      <div class="card-content white-text">
	      	<%= render 'form' %>
	   		</div>
			</div>
		</div>
	</div>

	 <div class="col s3 m3"></div>
	</div>
	<div class="row">
	    	<%= render @seats %>
  </div>