config/routes.rb
Rails.application.routes.draw do
  

  get 'admin/index'

  get "/pages/:page" => "pages#show", as: 'static'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'

  }



  resources :workshop
  resources :email
  resources :seats
  resources :shows
  resources :store_items
  resources :teachers
  resources :lessons
  resources :enrollments
  resources :gift_cards
  resources :instructed_classes
  resources :home
  root "home#index"

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :instructed_class
  belongs_to :user
end

app/models/gift_card.rb
class GiftCard < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  belongs_to :user
end

app/models/instructed_class.rb
class InstructedClass < ApplicationRecord
  belongs_to :lesson
  belongs_to :teacher
  has_many :enrollments, dependent: :destroy
  has_many :users, through: :enrollment
  
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
	has_many :instructed_classes, dependent: :destroy
	has_many :teachers, through: :instructed_classes
end

app/models/seat.rb
class Seat < ApplicationRecord
	has_many :show_seatings
  has_many :shows, through: :show_seating
end

app/models/show.rb
class Show < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :show_seatings
  has_many :seats, through: :show_seatings
  accepts_nested_attributes_for :show_seatings, :allow_destroy => true
  accepts_nested_attributes_for :seats, :allow_destroy => true
end

app/models/show_seating.rb
class ShowSeating < ApplicationRecord
  belongs_to :seat
  belongs_to :show
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
	has_many :instructed_classes, dependent: :destroy
	has_many :lessons, through: :instructed_classes
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :user, :teacher], multiple: false)                                      ##
  ############################################################################################ 
 
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :email, :uniqueness => true
  # validates_inclusion_of :roles, in: ['admin', 'teacher', 'user']

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	has_many :shows
	has_many :gift_cards
	has_many :store_items
	has_many :enrollments
	has_many :instructed_classes, through: :enrollments
	

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  access all: [:show, :index], user: {except: [:destroy, :create, :edit, :update]}, admin: :all

  # one other option that might seem a bit weird is to put a group of roles in an array:
  # access [:all, :user] => [:show, :index]

  def index
    @teachers = Teacher.all
    @teacher = Teacher.new
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new
    # User.create(email: params[:email], first_name:, roles: [:teacher])
    respond_to do |format|
      @teacher = Teacher.create(teacher_params)
      format.js
      format.html{redirect_to teachers_path}
    end
  end

  def show
    @lessons = Teacher.all
    @teacher = Teacher.find(params[:id])
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher.update(teacher_params)
    redirect_to teachers_path
  end

  def destroy
     respond_to do |format|
      @teacher = Teacher.find(params[:id]).destroy
      format.js
      format.html{redirect_to teachers_path}
    end
  end

   def teacher_params
    params.require(:teacher).permit(:name, :bio, :id, :avatar)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/gift_cards_helper.rb
module GiftCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/teachers/_form.html.erb
  
<div class="form">
    <%= form_with model: @teacher, class: "new_teacher", html: {multipart: true} do |f| %>
    	<%# f.label :class_name %>
        <%= f.text_field :name, placeholder: 'name', class: "form-control", id: "name" %>
        <br>
        <%# f.label :description %>
        <%= f.text_field :bio, placeholder: 'biography', class: "form-control", id: "bio" %>
       <br>
         <%= f.label :avatar, "add image" %>
        <br>
        <%= f.file_field :avatar, class:"button" %>
        <br>
        <%# f.select :roles, ['admin', 'teacher', 'user'], {}, {class: "form-control", id: "role"} %>
        <br>
        <%= f.email_field :email, placeholder: 'email', class: "form-control", id: "email" %>
        <br>
          <div class="black-text">
            <%= f.submit "ADD" %>
        </div>
    <% end %>
</div>	

app/views/teachers/_teacher.html.erb
  	<div class="col s3 m6">
  	<div class="<%= 'teacher' if local_assigns[:teacher] %>">
	    <div class="card horizontal">
	    	<div class="card-image">
       		<%= image_tag teacher.avatar.url(:thumb) %>
      	</div>
	      <div class="card-stacked">
	        <div class="card-content">
	        	<span class="card-title"><%= teacher.name %></span>
		          <p class="<%= 'part_bio' if !local_assigns[:part_bio] %>"><%= teacher.bio %></p>
		           <p><%# classes_taught %></p>
	        </div>
	        <% if !local_assigns[:hide_link] %>
		        <div class="card-action">
		        	<%= link_to "Find out more about me!", teacher_path(teacher) %>
		        	<% if logged_in?(:admin) %>   
			        	<%= link_to "delete", teacher, method: :delete, remote: true, class: "destroy_teacher float_right" %>
			 	        <%= link_to "edit", edit_teacher_path(teacher), class: "float_right" %>
		        		<%= link_to "delete", teacher, method: :delete, remote: true, class: "destroy_teacher float_right" %>
		 	          <%= link_to "edit", edit_teacher_path(teacher), class: "float_right" %>
		 	        <% end %>
		        </div>
		      <% end %>
	      </div>
	    </div>
	   </div>
	  </div>

app/views/teachers/create.html.erb
<h1>Teachers#create</h1>
<p>Find me in app/views/teachers/create.html.erb</p>

app/views/teachers/create.js.erb
$('.teachers').prepend("<%= j render @teacher %>");
$('.new_teacher').trigger('reset');

app/views/teachers/edit.html.erb
<div class="header">
	<h1>Edit Teacher</h1>
</div>
	
	<div class="row">
		<div class="col s3 m3"></div>
	  <div class="col s6 m6">
	    <div class="card grey darken-4">
	      <div class="card-content white-text">
	        <span class="card-title center">Edit Teacher</span>
	    		<%= render 'form' %>
	      </div>
	    </div>
	  </div>
	  	<div class="col s3 m3"></div>
	</div>

app/views/teachers/index.html.erb
<div class="header">
	<h1>Teachers</h1>
 	<div class="row">
	 	<div class="col l3 s3"></div>
	 	 <div class="col l6 s9">
	 	 	<div class="card grey darken-4">
	      <div class="card-content white-text">
	      	<% if user_signed_in? %>
	      			<%= link_to "Click here for Class Schedule", instructed_classes_path %>
	      		<% else %>
	      			<%= link_to "Login to start a class", user_session_path %>
	      		<% end %>
	   		</div>
			</div>
		</div>
	</div>
</div>

	<div class="row">
		<div class="col s3 m3"></div>
		<% if current_user && current_user.has_roles?(:admin) %> 
		  <div class="col s12 m6">
		    <div class="card grey darken-4">
		      <div class="card-content white-text">
		        <span class="card-title center">Add New Teacher</span>
		    		<%= render 'form' %>
		      </div>
		    </div>
		  </div>
		<% end %>
	  <div class="col s3 m3"></div>
	</div>
	<div class="row teachers">
	    	<%= render @teachers %>
  </div>

app/views/teachers/show.html.erb
<div class="header">
	<h1>Teachers</h1>
 	<div class="row">
	 	<div class="col l3 s3"></div>
	 	 <div class="col l6 s9">
	 	 	<div class="card grey darken-4">
	      <div class="card-content white-text">
	      	<% if user_signed_in? %>
	      			<%= link_to "Click here for Class Schedule", instructed_classes_path %>
	      		<% else %>
	      			<%= link_to "Login to start a class", user_session_path %>
	      		<% end %>
	   		</div>
			</div>
		</div>
	</div>
</div>
	<div class="row">
		<div class="col l3 s3"></div>
	  <%= render @teacher, hide_link: true, part_bio: true, teacher: false %>
  </div>
<div class="row">
</div>