config/routes.rb
Rails.application.routes.draw do
  

  get 'admin/index'

  get "/pages/:page" => "pages#show", as: 'static'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'

  }



  resources :workshop
  resources :email
  resources :seats
  resources :shows
  resources :store_items
  resources :teachers
  resources :lessons
  resources :enrollments
  resources :gift_cards
  resources :instructed_classes
  resources :home
  root "home#index"

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :instructed_class
  belongs_to :user
end

app/models/gift_card.rb
class GiftCard < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  belongs_to :user
end

app/models/instructed_class.rb
class InstructedClass < ApplicationRecord
  belongs_to :lesson
  belongs_to :teacher
  has_many :enrollments, dependent: :destroy
  has_many :users, through: :enrollment
  
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
	has_many :instructed_classes, dependent: :destroy
	has_many :teachers, through: :instructed_classes
end

app/models/seat.rb
class Seat < ApplicationRecord
	has_many :show_seatings
  has_many :shows, through: :show_seating
end

app/models/show.rb
class Show < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :show_seatings
  has_many :seats, through: :show_seatings
  accepts_nested_attributes_for :show_seatings, :allow_destroy => true
  accepts_nested_attributes_for :seats, :allow_destroy => true
end

app/models/show_seating.rb
class ShowSeating < ApplicationRecord
  belongs_to :seat
  belongs_to :show
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
	has_many :instructed_classes, dependent: :destroy
	has_many :lessons, through: :instructed_classes
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :user, :teacher], multiple: false)                                      ##
  ############################################################################################ 
 
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :email, :uniqueness => true
  # validates_inclusion_of :roles, in: ['admin', 'teacher', 'user']

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	has_many :shows
	has_many :gift_cards
	has_many :store_items
	has_many :enrollments
	has_many :instructed_classes, through: :enrollments
	

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  access all: [:show, :index], user: {except: [:destroy, :create, :edit, :update]}, admin: :all
  

  def index
    @shows = Show.all
    @show = Show.new
    # @seat = Seat.find_by_id(seat_params[:id])
    @show.show_seatings.build
    @seats = Seat.all
    @show_seating = ShowSeating.all
    @user = User.all
  end

  def new
    @show = Show.new
  end

  def create
    @show = Show.new
    respond_to do |format|
      @show = Show.create(show_params)
      format.js
      format.html{redirect_to shows_path}
    end
  end

  def show
    @show = Show.all
    @show = Show.find(params[:id])
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    @show.update(show_params)
    redirect_to shows_path
  end

  def destroy
     respond_to do |format|
      @show = Show.find(params[:id]).destroy
      format.js
      format.html{redirect_to shows_path}
    end
  end

   def show_params
    params.require(:show).permit(:title, :description, :date, 
      :time, :id, :avatar, show_seatings_attributes: [:seat_id, :cost, :quanity, :_destroy, :show_id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/gift_cards_helper.rb
module GiftCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/shows/_form.html.erb
<div class="form">
  <%= nested_form_for @show, class: "new_show", html: {multipart: true} do |f| %>

      <%# f.label :date %>
      <%= f.date_field :date, placeholder: 'date', class: "form-control", id: "date" %>
      <br>
      <%# f.label :time %>
      <%= f.time_field :time, placeholder: 'time', class: "form-control", id: "time" %>
      <br>
  	<%# f.label :title %>
      <%= f.text_field :title, placeholder: 'title', class: "form-control", id: "title" %>
      <br>
      <%# f.label :description %>
      <%= f.text_field :description, placeholder: 'description', class: "form-control", id: "description" %>
     <br>
      <table>
        <thead>
          <tr>
          <th>Seating Section</th>
          <th>Cost</th>
          <th>Quanity of seats</th>
          </tr>
        </thead>
        <tbody>
          <tr>
         <div class="row">
          <%= f.fields_for :show_seatings do |ss_form| %>
            <td class="line_width input-field"><%= ss_form.collection_select :seat_id, Seat.all, 'id', 'section' %></td>
            <td class="line_width"><%= ss_form.text_field :cost, placeholder: 'cost', class: "form-control", id: "cost" %></td>
            <td class="line_width"><%= ss_form.text_field :quanity, placeholder: 'quanity', class: "form-control", id: "quanity" %></td>
            </td>
          <% end %>
          </tr>
           <td class="line_width"><%= f.link_to_add "Add seat section", :show_seatings, id: 'add-show-seats'%></td>
            </div>
        </tbody>
      </table>

      <%= f.label :avatar, "add image" %>
      <br>
      <%= f.file_field :avatar, class:"button" %>
      <br>
      <br>
       <div class="black-text">
          <%= f.submit %>
      </div>
  <% end %>
</div>	

app/views/shows/_show.html.erb
  	<div class="col s6 m6 show">
	    <div class="card horizontal">
	    	<div class="card-image">
       		<%= image_tag show.avatar.url(:thumb) %>
      	</div>
	      <div class="card-stacked">
	        <div class="card-content">
	        	<span class="card-title">
	        		<p><%# show.date.strftime("%b %d, %Y") %></p>
		          <p><%# show.time.strftime("%I:%M:%S %p") %></p>
		          <p><%= show.title %></p>
		          <p><%= show.description %></p>
		          
	        </div>
	        <% if !local_assigns[:hide_link] %>
	        	<div class="card-action float_right">
	        		<p><%# show.show_seatings.seat %>
			          <%= form_with model: @show, scope: 'show', class: "book_seat"  do |f| %>
	        				<%= f.hidden_field :show_id, value: show.id %>
	        				<%# f.hidden_field :user_id, value: user.id %>
	        				<%= f.submit "book ticket", :disable_with => 'Submiting...' %>
	       				<% end %>
       				</p>
		        	<% if logged_in?(:admin) %>
		        		<%= link_to "delete", show, method: :delete, remote: true, class: "destroy_show float_right"%>
		 	          <%= link_to "edit", edit_show_path(show), class: "float_right" %>
		 	        <% end %>
	        </div>
	       <% end %>
	      </div>
	    </div>
	  </div>

app/views/shows/create.html.erb
<h1>Shows#create</h1>
<p>Find me in app/views/shows/create.html.erb</p>

app/views/shows/create.js.erb
$('.shows').prepend("<%= j render @show %>");
$('.new_show').trigger('reset');

app/views/shows/edit.html.erb
<div class="header">
	<h1>Edit Show</h1>
</div>

	<div class="row">
		<div class="col s3 m3"></div>
	  <div class="col s6 m6">
	    <div class="card grey darken-4">
	      <div class="card-content white-text">
	        <!-- <span class="card-title">Edit Show</span> -->
	    		<%= render 'form' %>
	      </div>
	    </div>
	  </div>
	  <div class="col s3 m3"></div>
	</div>

app/views/shows/index.html.erb
<div class="header">
	<h1>Up Coming Shows</h1>
<!-- 	<p>call to action link</p> -->
</div>
<div class="container-fluid">
	<div class="row">
		<div class="col s3 m3"></div>
		<% if logged_in?(:admin) %>
		  <div class="col s12 m6">
		    <div class="card grey darken-4">
		      <div class="card-content white-text">
		         <ul class="collapsible" data-collapsible="accordion">
					    <li>
					      <div class="collapsible-header black-text"><i class="material-icons">filter_drama</i>Create New Show</div>
					      <div class="collapsible-body">
					      	<span>		<%= render 'form' %></span>
					      </div>
					    </li>
					    <li>
					      <div class="collapsible-header black-text"><i class="material-icons">place</i>Edit Seating Chart</div>
					      <div class="collapsible-body"><span><%= link_to "Edit Seating Chart", seats_path %></span></div>
					    </li>
					    <li>
					      <!-- <div class="collapsible-header black-text	"><i class="material-icons">whatshot</i>Show Seating</div>
					      <div class="collapsible-body">
					      	<span>Lorem ipsum dolor sit amet.</span>
					      </div> -->
					    </li>
					  </ul>
		      </div>
		    </div>
		  </div>
	 	<% end %>
	  <div class="col s3 m3"></div>
	</div>
	<div class="row shows">
	    	<%= render @shows %>
  </div>
</div>

app/views/shows/new.html.erb
<h1>Shows#new</h1>
<p>Find me in app/views/shows/new.html.erb</p>

app/views/shows/show.html.erb
<h1>Shows#show</h1>
<p>Find me in app/views/shows/show.html.erb</p>